# Generated by Django 6.0.4 on 2026-06-03 13:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Montant')),
                ('date_paiement', models.DateTimeField(verbose_name='Date de paiement')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Référence')),
                ('mode_paiement', models.CharField(choices=[('especes', 'Espèces'), ('virement', 'Virement bancaire'), ('wave', 'Wave'), ('orange_money', 'Orange Money'), ('free_money', 'Free Money'), ('carte', 'Carte bancaire'), ('autre', 'Autre')], max_length=20, verbose_name='Mode de paiement')),
                ('solde_restant', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Solde restant')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-date_paiement'],
            },
        ),
    ]
