# Generated by Django 6.0.4 on 2026-06-19 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_numero_recu'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='invoice_token',
            field=models.CharField(blank=True, max_length=100, verbose_name='Token PayDunya'),
        ),
        migrations.AddField(
            model_name='payment',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('confirme', 'Confirmé'), ('echoue', 'Échoué'), ('rembourse', 'Remboursé')], default='en_attente', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='mode_paiement',
            field=models.CharField(choices=[('especes', 'Espèces'), ('virement', 'Virement bancaire'), ('wave', 'Wave'), ('orange_money', 'Orange Money'), ('free_money', 'Free Money'), ('carte', 'Carte bancaire'), ('paydunya', 'PayDunya'), ('autre', 'Autre')], default='paydunya', max_length=20, verbose_name='Mode de paiement'),
        ),
    ]
