# Generated by Django 6.0.4 on 2026-07-08 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_invoice_token_payment_statut_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='mode_paiement',
        ),
    ]
