# Generated by Django 6.0.6 on 2026-08-07 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_remove_payment_mode_paiement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='invoice_token',
        ),
    ]
