# Generated by Django 6.0.6 on 2026-08-07 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_remove_payment_invoice_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='paytech_token',
            field=models.CharField(blank=True, max_length=100, verbose_name='Token PayTech'),
        ),
    ]
