# Generated by Django 6.0.4 on 2026-08-07 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_payment_paytech_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='est_achat_carte',
            field=models.BooleanField(default=False, verbose_name='Achat carte membre'),
        ),
    ]
