# Generated by Django 6.0.4 on 2026-06-02 22:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('photo', models.ImageField(blank=True, upload_to='photos/', verbose_name='Photo')),
                ('promotion_bac', models.IntegerField(blank=True, null=True, verbose_name='Promotion du Bac')),
                ('serie', models.CharField(blank=True, choices=[('S', 'Scientifique'), ('L', 'Littéraire'), ('ES', 'Économique et Social'), ('STMG', 'STMG'), ('STI2D', 'STI2D'), ('AUTRE', 'Autre')], max_length=10, verbose_name='Série du Bac')),
                ('universite', models.CharField(blank=True, max_length=200, verbose_name='Université / École')),
                ('filiere', models.CharField(blank=True, max_length=200, verbose_name="Filière d'étude")),
                ('profession', models.CharField(blank=True, max_length=200, verbose_name='Profession')),
                ('bio', models.TextField(blank=True, verbose_name='Biographie / Conseils')),
                ('adresse', models.TextField(blank=True, verbose_name='Adresse')),
                ('date_naissance', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('est_mentor', models.BooleanField(default=False, verbose_name='Peut être mentor')),
                ('est_visible', models.BooleanField(default=True, verbose_name='Profil visible')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil',
                'verbose_name_plural': 'Profils',
                'ordering': ['-created_at'],
            },
        ),
    ]
