# Generated by Django 6.0.4 on 2026-06-06 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_add_numero_membre'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='carte_achetee',
            field=models.BooleanField(default=False, verbose_name='Carte membre achetée'),
        ),
        migrations.AddField(
            model_name='profile',
            name='date_achat_carte',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date d'achat de la carte"),
        ),
    ]
