# Generated by Django 6.0.4 on 2026-06-15 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_carte_achetee_profile_date_achat_carte'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='statut',
            field=models.CharField(blank=True, choices=[('nouveau_bachelier', 'Nouveau bachelier'), ('etudiant', 'Étudiant'), ('professionnel', 'Professionnel'), ('diplome', 'Diplômé')], max_length=20, verbose_name='Statut'),
        ),
    ]
