# Generated by Django 6.0.4 on 2026-08-10 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_profile_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='niveau_etude',
            field=models.CharField(blank=True, choices=[('bac', 'Baccalauréat'), ('licence1', 'Licence 1'), ('licence2', 'Licence 2'), ('licence3', 'Licence 3'), ('master1', 'Master 1'), ('master2', 'Master 2'), ('doctorat', 'Doctorat'), ('autre', 'Autre')], max_length=20, verbose_name="Niveau d'étude"),
        ),
    ]
