# Generated by Django 6.0.4 on 2026-06-03 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('type_event', models.CharField(choices=[('orientation', "Journée d'orientation"), ('reunion', 'Réunion'), ('formation', 'Formation'), ('conference', 'Conférence'), ('social', 'Événement social'), ('autre', 'Autre')], default='autre', max_length=20, verbose_name='Type')),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('lieu', models.CharField(max_length=200, verbose_name='Lieu')),
                ('max_participants', models.IntegerField(blank=True, null=True, verbose_name='Nombre max de participants')),
                ('est_public', models.BooleanField(default=True, verbose_name='Événement public')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organized_events', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(blank=True, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Événement',
                'verbose_name_plural': 'Événements',
                'ordering': ['-date'],
            },
        ),
    ]
