# Generated by Django 6.0.4 on 2026-06-06 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='numero_membre',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Numéro de membre'),
        ),
    ]
