# Generated by Django 6.0.4 on 2026-06-15 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Offre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('type', models.CharField(choices=[('stage', 'Stage'), ('emploi', 'Emploi'), ('concours', 'Concours')], max_length=20, verbose_name='Type')),
                ('description', models.TextField(verbose_name='Description')),
                ('organisation', models.CharField(blank=True, max_length=200, verbose_name='Organisation / Entreprise')),
                ('lieu', models.CharField(blank=True, max_length=200, verbose_name='Lieu')),
                ('date_limite', models.DateField(blank=True, null=True, verbose_name='Date limite')),
                ('lien', models.URLField(blank=True, verbose_name='Lien')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Email de contact')),
                ('est_public', models.BooleanField(default=True, verbose_name='Publique')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offres', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Offre',
                'verbose_name_plural': 'Offres',
                'ordering': ['-created_at'],
            },
        ),
    ]
