# Generated by Django 6.0.4 on 2026-06-03 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentorship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('acceptee', 'Acceptée'), ('refusee', 'Refusée'), ('terminee', 'Terminée')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('message', models.TextField(blank=True, verbose_name='Message du demandeur')),
                ('date_debut', models.DateTimeField(blank=True, null=True, verbose_name='Date de début')),
                ('date_fin', models.DateTimeField(blank=True, null=True, verbose_name='Date de fin')),
                ('commentaires', models.TextField(blank=True, verbose_name='Commentaires')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mentee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentorships_as_mentee', to=settings.AUTH_USER_MODEL)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentorships_as_mentor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mentorat',
                'verbose_name_plural': 'Mentorats',
                'ordering': ['-created_at'],
                'unique_together': {('mentor', 'mentee')},
            },
        ),
    ]
