# Generated by Django 6.0.4 on 2026-06-03 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('fichier', models.FileField(upload_to='documents/', verbose_name='Fichier')),
                ('categorie', models.CharField(choices=[('statuts', 'Statuts'), ('reglement', 'Règlement intérieur'), ('pv', 'Procès-verbal'), ('rapport_financier', 'Rapport financier'), ('rapport_activite', "Rapport d'activités"), ('guide', "Guide d'orientation universitaire"), ('autre', 'Autre')], default='autre', max_length=20, verbose_name='Catégorie')),
                ('est_public', models.BooleanField(default=True, verbose_name='Document public')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-created_at'],
            },
        ),
    ]
